---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nft-promo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nft-promo
  template:
    metadata:
      labels:
        app: nft-promo
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: deo
          image: ghcr.io/opolis/nft-promo:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nft-promo
spec:
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: http
  selector:
    app: nft-promo
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nft-promo-ingress
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
spec:
  rules:
  - host: nft-promo-testing.opolis.co
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nft-promo
            port:
              number: 3000
  tls:
   - hosts:
       - nft-promo-testing.opolis.co
     secretName: nft-promo-tls