/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20 } from "./ERC20"
export type { Faucet } from "./Faucet"

export { ERC20__factory } from "./factories/ERC20__factory"
export { Faucet__factory } from "./factories/Faucet__factory"
