name: Build Docker Images

on:
  pull_request:
    branches: [ dev ]
  push:
    tags:
      - 'v*'
    branches: [ '*' ]

jobs:

  build-images:
    name: Build Docker Images
    runs-on: ubuntu-latest
    steps:
      # Check out code
      - name: Checkout
        uses: actions/checkout@v2

      # Determine tag we will use for images
      - name: Get Image Version
        shell: bash
        run: |
          echo ::set-output name=tag::$([[ "${GITHUB_REF##*/}" == "dev" ]] && echo latest || echo ${GITHUB_REF##*/})
        id: version

      # Login to the container registry
      - name: Login to Container Registry
        run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
        if: ${{ github.event_name != 'pull_request' }}

      # Build and push the image
      - name: Build and Push Server Image
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' && (github.ref == 'refs/heads/dev' || startsWith(github.ref, 'refs/tags/v')) }}
          tags: ghcr.io/opolis/nft-promo:${{ steps.version.outputs.tag }}

